spring.application.name=gerenciador-pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/Gerenciador-Pedidos
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update